# Barrel, the backend of the Musikverein Leopoldsdorf.
# Copyright (C) 2021  Richard Stöckl
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Test1234
  jpa:
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api/v1
  ldap:
    base: dc=mvl,dc=at
    username: cn=admin,dc=mvl,dc=at
    password: adminpassword
    urls:
      - ldap://localhost:1389
logging:
  level:
    org.springframework.data: debug
    org.springframework.security: debug
    org.springframework.ldap: debug
    at.mvl.barrel: trace
server:
  port: 7380
